name: Build & Push

on: [push, pull_request]
# on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

env:
  REPOSITORY_PATH: dfinance/gh-actions
  REGISTRY: docker.pkg.github.com

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Build and push docker image to dockerhub
      run: |
        export BRANCH=$(sed -e 's/refs\/tags\///g; s/refs\/heads\///g;' <<< ${GITHUB_REF})

        docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
        docker build -f ./.build/Dockerfile -t ${REPOSITORY_PATH}:${BRANCH} -t ${REPOSITORY_PATH}:latest .
        docker push ${REPOSITORY_PATH}:${BRANCH}
        docker push ${REPOSITORY_PATH}:latest
        docker logout

    - name: Build and push docker image to github
      run: |
        export BRANCH=$(sed -e 's/refs\/tags\///g; s/refs\/heads\///g;' <<< ${GITHUB_REF})

        docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_PASSWORD }} ${REGISTRY}
        docker build -f ./.build/Dockerfile -t ${REPOSITORY_PATH}:${BRANCH} -t ${REPOSITORY_PATH}:latest .
        docker push ${REPOSITORY_PATH}:${BRANCH}
        docker push ${REPOSITORY_PATH}:latest
        docker logout
