name: Build & Push

on: [push, pull_request]
# on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

env:
  GITHUB_REGISTRY: docker.pkg.github.com
  GITHUB_REPOSITORY_PATH: docker.pkg.github.com/dfinance/gh-actions/gh-actions
  REPOSITORY_PATH: dfinance/gh-actions

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Build and push docker image to dockerhub
      uses: dfinance/gh-actions@master
      with:
        name: ${REPOSITORY_PATH}
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        cache: true

    - name: Build and push docker image to github
      uses: dfinance/gh-actions@master
      with:
        name: ${GITHUB_REPOSITORY_PATH}
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        cache: true
        registry: docker.pkg.github.com
        # dockerfile: Dockerfile

    # - name: Build and push docker image to dockerhub
    #   run: |
    #     export BRANCH=$(sed -e 's/refs\/tags\///g; s/refs\/heads\///g;' <<< ${GITHUB_REF})

    #     docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
    #     docker build -f ./Dockerfile -t ${REPOSITORY_PATH}:${BRANCH} -t ${REPOSITORY_PATH}:latest .
    #     docker push ${REPOSITORY_PATH}:${BRANCH}
    #     docker push ${REPOSITORY_PATH}:latest
    #     docker logout

    # - name: Build and push docker image to github
    #   run: |
    #     export BRANCH=$(sed -e 's/refs\/tags\///g; s/refs\/heads\///g;' <<< ${GITHUB_REF})

    #     docker login -u ${GITHUB_ACTOR} -p ${{ secrets.GITHUB_TOKEN }} ${GITHUB_REGISTRY}
    #     docker build -f ./Dockerfile -t ${GITHUB_REPOSITORY_PATH}:${BRANCH} -t ${GITHUB_REPOSITORY_PATH}:latest .
    #     docker push ${GITHUB_REPOSITORY_PATH}:${BRANCH}
    #     docker push ${GITHUB_REPOSITORY_PATH}:latest
    #     docker logout
